<?php


class UnitLeadContactTableSeeder extends DatabaseSeeder {
	public function run() {

		Eloquent::unguard();

		DB::table( 'unit_lead_contacts' )->delete();

		$unit_lead_contacts = [
			'FIPRA Argentina (Full Member)'                              => 'Miguel Ángel Martínez',
			'FIPRA Australia (Full Member)'                              => 'John Richardson',
			'FIPRA Austria (Full Member)'                                => 'Peter Koppl',
			'FIPRA Belgium (Full Member)'                                => 'Peter Tulkens',
			'FIPRA Brazil (Full Member)'                                 => 'José Gabriel Assis de Almeida',
			'FIPRA Bulgaria (Full Member)'                               => 'Rositsa Velkova',
			'FIPRA Canada (Full Member)'                                 => 'Andre Albinati',
			'FIPRA China (Full Member)'                                  => 'Haiying Yuan',
			'FIPRA Croatia (Full Member)'                                => 'Natko Vlahovic',
			'FIPRA Czech Republic (Full Member)'                         => 'Jana Marco',
			'FIPRA Denmark (Full Member)'                                => 'Lars Abel',
			'FIPRA Estonia (Full Member)'                                => 'Andreas Kaju',
			'FIPRA Finland (Full Member)'                                => 'Ilari Marzano',
			'FIPRA France (Full Member)'                                 => 'Thaima Samman',
			'FIPRA Germany (Full Member)'                                => 'Dominik Meier',
			'FIPRA Greece (Full Member)'                                 => 'Costas Yiannopoulos',
			'FIPRA Hungary (Full Member)'                                => 'Tamás Sárdi',
			'FIPRA India (Full Member)'                                  => 'Manash Neog',
			'FIPRA International UK (Full Member)'                       => 'Rory Chisholm',
			'FIPRA International BE (Full Member)'                       => 'Laura Batchelor',
			'FIPRA Ireland (Full Member)'                                => 'Lucinda Creighton',
			'FIPRA Italy (Full Member)'                                  => 'Mariella Palazzolo',
			'FIPRA Japan (Full Member)'                                  => 'Philip Howard',
			'FIPRA Kazakhstan (Full Member)'                             => 'Evgeny Roshkov',
			'FIPRA Kyrgyzstan (Full Member)'                             => 'Evgeny Roshkov',
			'FIPRA Latvia (Full Member)'                                 => 'Armands Gutmanis',
			'FIPRA Lithuania (Full Member)'                              => 'Arūnas Pemkus',
			'FIPRA Mongolia (Full Member)'                               => 'Evgeny Roshkov',
			'FIPRA Mexico (Full Member)'                                 => 'Juan Mauricio Mora',
			'FIPRA Netherlands (Full Member)'                            => 'Peter van Keulen',
			'FIPRA Norway (Full Member)'                                 => 'Per Høiby',
			'FIPRA Poland (Full Member)'                                 => 'Marek Matraszek',
			'FIPRA Portugal (Full Member)'                               => 'Ana Vila Nova',
			'FIPRA Romania (Full Member)'                                => 'Danut Nicolae',
			'FIPRA Russia (Full Member)'                                 => 'Evgeny Roshkov',
			'FIPRA Singapore (Full Member)'                              => 'Richard Andrew',
			'FIPRA Slovakia (Full Member)'                               => 'Patrik Zoltvany',
			'FIPRA Slovenia (Full Member)'                               => 'Mihael Cigler',
			'FIPRA South Africa (Full Member)'                           => 'Abdul Waheed Patel',
			'FIPRA South Korea (Full Member)'                            => 'Joseph Chung',
			'FIPRA Spain (Full Member)'                                  => 'Sebastian Mariz',
			'FIPRA Sweden (Full Member)'                                 => 'Marten Wennberg',
			'FIPRA Switzerland (Full Member)'                            => 'Dominique Reber',
			'FIPRA Tajikistan (Full Member)'                             => 'Evgeny Roshkov',
			'FIPRA Turkey (Full Member)'                                 => 'Ayse Aricioglu',
			'FIPRA Turkmenistan (Full Member)'                           => 'Evgeny Roshkov',
			'FIPRA United Kingdom (Full Member)'                         => 'Michael Craven',
			'FIPRA Ukraine (Full Member)'                                => 'Ivan Poltavets',
			'FIPRA USA (Full Member)'                                    => 'Rhod Shaw',
			'FIPRA Uzbekistan (Full Member)'                             => 'Evgeny Roshkov',
			'FIPRA Azerbaijan (Country Representative - Leila Alieva)'   => 'Leila Alieva',
			'FIPRA Azerbaijan (Country Representative - Sadya Aliyev)'   => 'Sadyar Aliyev',
			'FIPRA Colombia (Country Representative)'                    => 'Nicola Montorsi',
			'FIPRA Cyprus (Country Representative)'                      => 'Achilleas Demetriades',
			'FIPRA France (Country Representative)'                      => 'Jean-Francois Guichard',
			'FIPRA Georgia (Country Representative)'                     => 'Lasha Gogiberidze',
			'FIPRA Hong Kong (Country Representative)'                   => 'Greg Shea',
			'FIPRA Iceland (Country Representative)'                     => 'Alp Mehmet',
			'FIPRA India (Country Representative)'                       => 'Raman Chada',
			'FIPRA Kazakhstan (Country Representative)'                  => 'Ruslan Zhemkov',
			'FIPRA Luxembourg (Country Representative)'                  => 'Joe Huggard',
			'FIPRA Malta (Country Representative)'                       => 'Martin Cauchi Inglott',
			'FIPRA South Africa (Country Representative - John Mare)'    => 'John Mare',
			'FIPRA South Africa (Country Representative - Jenni Newman)' => 'Jenni Newman',
			'FIPRA Sweden (Country Representative)'                      => 'Anders Rostin',
			'FIPRA Tunisia (Country Representative)'                     => 'Ghazi Ben Ahmed',
			'FIPRA USA - California (Country Representative)'            => 'Rory Faber',
			'FIPRA USA - Texas (Country Representative)'                 => 'Russ Keene',
		];

		$unit_rate_bands = [
			'FIPRA Argentina (Full Member)'                              => 'low',
			'FIPRA Australia (Full Member)'                              => 'high',
			'FIPRA Austria (Full Member)'                                => 'high',
			'FIPRA Belgium (Full Member)'                                => 'high',
			'FIPRA Brazil (Full Member)'                                 => 'low',
			'FIPRA Bulgaria (Full Member)'                               => 'low',
			'FIPRA Canada (Full Member)'                                 => 'high',
			'FIPRA China (Full Member)'                                  => 'high',
			'FIPRA Croatia (Full Member)'                                => 'low',
			'FIPRA Czech Republic (Full Member)'                         => 'low',
			'FIPRA Denmark (Full Member)'                                => 'high',
			'FIPRA Estonia (Full Member)'                                => 'low',
			'FIPRA Finland (Full Member)'                                => 'high',
			'FIPRA France (Full Member)'                                 => 'high',
			'FIPRA Germany (Full Member)'                                => 'high',
			'FIPRA Greece (Full Member)'                                 => 'low',
			'FIPRA Hungary (Full Member)'                                => 'low',
			'FIPRA India (Full Member)'                                  => 'low',
			'FIPRA International UK (Full Member)'                       => 'high',
			'FIPRA International BE (Full Member)'                       => 'high',
			'FIPRA Ireland (Full Member)'                                => 'high',
			'FIPRA Italy (Full Member)'                                  => 'high',
			'FIPRA Japan (Full Member)'                                  => 'high',
			'FIPRA Kazakhstan (Full Member)'                             => 'low',
			'FIPRA Kyrgyzstan (Full Member)'                             => 'low',
			'FIPRA Latvia (Full Member)'                                 => 'low',
			'FIPRA Lithuania (Full Member)'                              => 'low',
			'FIPRA Mongolia (Full Member)'                               => 'low',
			'FIPRA Mexico (Full Member)'                                 => 'low',
			'FIPRA Netherlands (Full Member)'                            => 'high',
			'FIPRA Norway (Full Member)'                                 => 'high',
			'FIPRA Poland (Full Member)'                                 => 'low',
			'FIPRA Portugal (Full Member)'                               => 'low',
			'FIPRA Romania (Full Member)'                                => 'low',
			'FIPRA Russia (Full Member)'                                 => 'low',
			'FIPRA Singapore (Full Member)'                              => 'high',
			'FIPRA Slovakia (Full Member)'                               => 'low',
			'FIPRA Slovenia (Full Member)'                               => 'low',
			'FIPRA South Africa (Full Member)'                           => 'low',
			'FIPRA South Korea (Full Member)'                            => 'high',
			'FIPRA Spain (Full Member)'                                  => 'low',
			'FIPRA Sweden (Full Member)'                                 => 'high',
			'FIPRA Switzerland (Full Member)'                            => 'high',
			'FIPRA Tajikistan (Full Member)'                             => 'low',
			'FIPRA Turkey (Full Member)'                                 => 'low',
			'FIPRA Turkmenistan (Full Member)'                           => 'low',
			'FIPRA United Kingdom (Full Member)'                         => 'high',
			'FIPRA Ukraine (Full Member)'                                => 'low',
			'FIPRA USA (Full Member)'                                    => 'high',
			'FIPRA Uzbekistan (Full Member)'                             => 'low',
			'FIPRA Azerbaijan (Country Representative - Leila Alieva)'   => 'low',
			'FIPRA Azerbaijan (Country Representative - Sadya Aliyev)'   => 'low',
			'FIPRA Colombia (Country Representative)'                    => 'low',
			'FIPRA Cyprus (Country Representative)'                      => 'low',
			'FIPRA France (Country Representative)'                      => 'high',
			'FIPRA Georgia (Country Representative)'                     => 'low',
			'FIPRA Hong Kong (Country Representative)'                   => 'low',
			'FIPRA Iceland (Country Representative)'                     => 'low',
			'FIPRA India (Country Representative)'                       => 'low',
			'FIPRA Kazakhstan (Country Representative)'                  => 'low',
			'FIPRA Luxembourg (Country Representative)'                  => 'low',
			'FIPRA Malta (Country Representative)'                       => 'low',
			'FIPRA South Africa (Country Representative - John Mare)'    => 'low',
			'FIPRA South Africa (Country Representative - Jenni Newman)' => 'low',
			'FIPRA Sweden (Country Representative)'                      => 'high',
			'FIPRA Tunisia (Country Representative)'                     => 'low',
			'FIPRA USA - California (Country Representative)'            => 'high',
			'FIPRA USA - Texas (Country Representative)'                 => 'high',
		];

		$lead_contact_emails = [
			'John Richardson'               => 'johnl.richardson@fipra.com',
			'José Gabriel Assis de Almeida' => 'jose.almeida@fipra.com',
			'Rositsa Velkova'               => 'rositsa.velkova@fipra.com',
			'Andre Albinati'                => 'andre.albinati@fipra.com',
			'Haiying Yuan'                  => 'haiying.yuan@fipra.com',
			'Natko Vlahovic'                => 'natko.vlahovic@fipra.com',
			'Andreas Hadjikyriacos'         => 'andreas.hadjikyriacos@fipra.com',
			'Jana Marco'                    => 'jana.marco@fipra.com',
			'Lars Abel'                     => 'lars.abel@fipra.com',
			'Andreas Kaju'                  => 'andreas.kaju@fipra.com',
			'Ilari Marzano'                 => 'ilari.marzano@fipra.com',
			'Jean Francois Guichard'        => 'jeanfrancois.guichard@fipra.com',
			'Dominik Meier'                 => 'dominik.meier@fipra.com',
			'Costas Yiannopoulos'           => 'costas.yiannopoulos@fipra.com',
			'Tamás Sárdi'                   => 'tamas.sardi@fipra.com',
			'Manash Neog'                   => 'manash.neog@fipra.com',
			'Peter-Carlo Lehrell'           => 'mark.fielding@fipra.com',
			'Ann Kelly'                     => 'ann.kelly@fipra.com',
			'Mariella Palazzolo'            => 'mariella.palazzolo@fipra.com',
			'Philip Howard'                 => 'philip.howard@fipra.com',
			'Yun-Hee Lee'                   => 'yunhee.lee@fipra.com',
			'Armands Gutmanis'              => 'armands.gutmanis@fipra.com',
			'Arūnas Pemkus'                 => 'arunas.pemkus@fipra.com',
			'Ukko Metsola'                  => 'ukko.metsola@fipra.com',
			'Miriam Offermans'              => 'miriam.offermans@fipra.com',
			'Per Høiby'                     => 'per.hoiby@fipra.com',
			'Marek Matraszek'               => 'marek.matraszek@fipra.com',
			'Ana Vila Nova'                 => 'ana.vilanova@fipra.com',
			'Alex Andreev'                  => 'alex.andreev@fipra.com',
			'Patrik Zoltvany'               => 'patrik.zoltvany@fipra.com',
			'Mihael Cigler'                 => 'mihael.cigler@fipra.com',
			'Sebastian Mariz'               => 'sebastian.mariz@fipra.com',
			'Göran Thorstenson'             => 'goran.thorstenson@fipra.com',
			'Dominique Reber'               => 'dominique.reber@fipra.com',
			'Ayse Aricioglu'                => 'ayse.aricioglu@fipra.com',
			'Rory Chisholm'                 => 'rory.chisholm@fipra.com',
			'Abdul Waheed Patel'            => 'abdulwaheed.patel@fipra.com',
			'Sayer Aliyev'                  => 'sayer.aliyev@fipra.com',
			'Richard Andrew'                => 'richard.andrew@fipra.com',
			'Jose Luis Echevarria'          => 'joseluis.echevarria@fipra.com',
			'Peter van Keulen'              => 'peter.vankeulen@fipra.com',
			'Anders Rostin'                 => 'anders.rostin@fipra.com',
			'Lasha Gogiberidze'             => 'lasha.gogiberidze@fipra.com',
			'Mark Fielding'                 => 'mark.fielding@fipra.com',
			'Markus Schindler'              => 'markus.schindler@fipra.com',
			'Ivan Poltavets'                => 'ivan.poltavets@fipra.com',
			'Michael Craven'                => 'michael.craven@fipra.com',
			'Adrian Fielding'               => 'adrian.fielding@fipra.com',
			'Miguel Ángel Martínez'         => 'miguel.angelmartinez@fipra.com',
			'Danut Nicolae'                 => 'danut.nicolae@fipra.com',
			'Evgeny Roshkov'                => 'evgeny.roshkov@fipra.com',
			'Thaima Samman'                 => 'thaima.samman@fipra.com',
			'Lucinda Creighton'             => 'lucinda.creighton@fipra.com',
			'Michael Craven'                => 'michael.craven@fipra.com',
			'Yongbai Cho'                   => 'yongbai.cho@fipra.com',
			'Abdullah Nassief'              => 'abdullah.nassief@fipra.com',
			'Martin Cauchi Inglott'         => 'martin.cauchiinglott@fipra.com',
			'Joseph Chung'                  => 'joseph.chung@fipra.com',
			'Sadyar Aliyev'                 => 'sadyar.aliyev@fipra.com',
			'Nicola Montorsi'               => 'nicola.montorsi@fipra.com',
			'Achilleas Demetriades'         => 'achilleas.demetriades@fipra.com',
			'Jean-Francois Guichard'        => 'jeanfrancois.guichard@fipra.com',
			'Lasha Gogiberidze'             => 'lasha.gogiberidze@fipra.com',
			'Greg Shea'                     => 'greg.shea@fipra.com',
			'Alp Mehmet'                    => 'alp.mehmet@fipra.com',
			'Ruslan Zhemkov'                => 'ruslan.zhemkov@fipra.com',
			'Joe Huggard'                   => 'joe.huggard@fipra.com',
			'Martin Cauchi-Inglott'         => 'martin.cauchiinglott@fipra.com',
			'Anders Rostin'                 => 'anders.rostin@fipra.com',
			'Ghazi Ben Ahmed'               => 'ghazi.benahmed@fipra.com',
			'Rory Faber'                    => 'rory.faber@fipra.com',
			'Russ Keene'                    => 'russ.keene@fipra.com',
			'Marten Wennberg'               => 'marten.wennberg@fipra.com',
			'Leila Alieva'                  => 'leila.alieva@fipra.com',
			'Juan Mauricio Mora'            => 'jmmora@fipra.com',
			'Rhod Shaw'                     => 'rhod.shaw@fipra.com',
			'Raman Chada'                   => 'raman.chada@fipra.com',
			'John Mare'                     => 'john.mare@fipra.com',
			'Jenni Newman'                  => 'jenni.newman@fipra.com',
			'Laura Batchelor'               => 'laura.batchelor@fipra.com',
			'Peter Koppl'                   => 'peter.koppl@fipra.com',
			'Peter Tulkens'                 => 'peter.tulkens@fipra.com',
		];

		$unit_additional_info = [
			'FIPRA International BE (Full Member)' => 'Billing details:\\nFipra International SRL,\\nRue de la Loi 227,\\nBrussels 1040,\\nBelgium,\\nVAT No: BE 0733.774.811'
		];

		foreach ( $unit_lead_contacts as $unit => $contact ) {
			Unit_lead_contact::create(
				[
					'unit_name'         => $unit,
					'lead_contact_name' => $contact,
					'email'             => isset( $lead_contact_emails[ $contact ] ) ? $lead_contact_emails[ $contact ] : '',
					'rate_band'         => $unit_rate_bands[ $unit ],
					'additional_info'   => isset( $unit_additional_info[ $unit ] ) ? $unit_additional_info[ $unit ] : '',
				]
			);
		}
	}
}