<?php


class UnitLeadContactTableSeeder extends DatabaseSeeder {
	public function run() {

		Eloquent::unguard();

		DB::table( 'unit_lead_contacts' )->delete();

		$unit_lead_contacts = [
			'FIPRA Argentina (Unit)'                                   => 'Miguel Ángel Martínez',
			'FIPRA Australia (Unit)'                                   => 'John Richardson',
			'FIPRA Austria (Unit)'                                     => '',
			'FIPRA Brazil (Unit)'                                      => 'José Gabriel Assis de Almeida',
			'FIPRA Bulgaria (Unit)'                                    => 'Rositsa Velkova',
			'FIPRA Canada (Unit)'                                      => 'Andre Albinati',
			'FIPRA China (Unit)'                                       => 'Haiying Yuan',
			'FIPRA Croatia (Unit)'                                     => 'Natko Vlahovic',
			'FIPRA Czech Republic (Unit)'                              => 'Jana Marco',
			'FIPRA Denmark (Unit)'                                     => 'Lars Abel',
			'FIPRA Estonia (Unit)'                                     => 'Andreas Kaju',
			'FIPRA Finland (Unit)'                                     => 'Ilari Marzano',
			'FIPRA France (Unit)'                                      => 'Thaima Samman',
			'FIPRA Germany (Unit)'                                     => 'Dominik Meier',
			'FIPRA Greece (Unit)'                                      => 'Anthony Gortzis',
			'FIPRA Hungary (Unit)'                                     => 'Tamás Sárdi',
			'FIPRA India (Unit)'                                       => 'Manash Neog',
			'FIPRA International BE (Unit)'                            => '',
			'FIPRA International UK (Unit)'                            => 'Rory Chisholm',
			'FIPRA Ireland (Unit)'                                     => 'Lucinda Creighton',
			'FIPRA Italy (Unit)'                                       => 'Mariella Palazzolo',
			'FIPRA Japan (Unit)'                                       => 'Philip Howard',
			'FIPRA Kazakhstan (Unit)'                                  => 'Evgeny Roshkov',
			'FIPRA Kyrgyzstan (Unit)'                                  => 'Evgeny Roshkov',
			'FIPRA Latvia (Unit)'                                      => 'Armands Gutmanis',
			'FIPRA Lithuania (Unit)'                                   => 'Arūnas Pemkus',
			'FIPRA Mongolia (Unit)'                                    => 'Evgeny Roshkov',
			'FIPRA Mexico (Unit)'                                      => 'Juan Mauricio Mora',
			'FIPRA Netherlands (Unit)'                                 => 'Peter van Keulen',
			'FIPRA Norway (Unit)'                                      => 'Per Høiby',
			'FIPRA Poland (Unit)'                                      => 'Marek Matraszek',
			'FIPRA Portugal (Unit)'                                    => 'Ana Vila Nova',
			'FIPRA Romania (Unit)'                                     => 'Danut Nicolae',
			'FIPRA Russia (Unit)'                                      => 'Evgeny Roshkov',
			'FIPRA Singapore (Unit)'                                   => 'Richard Andrew',
			'FIPRA Slovakia (Unit)'                                    => 'Patrik Zoltvany',
			'FIPRA Slovenia (Unit)'                                    => 'Mihael Cigler',
			'FIPRA South Africa (Unit)'                                => 'Abdul Waheed Patel',
			'FIPRA South Korea (Unit)'                                 => 'Joseph Chung',
			'FIPRA Spain (Unit)'                                       => 'Sebastian Mariz',
			'FIPRA Sweden (Unit)'                                      => 'Marten Wennberg',
			'FIPRA Switzerland (Unit)'                                 => 'Dominique Reber',
			'FIPRA Tajikistan (Unit)'                                  => 'Evgeny Roshkov',
			'FIPRA Turkey (Unit)'                                      => 'Ayse Aricioglu',
			'FIPRA Turkmenistan (Unit)'                                => 'Evgeny Roshkov',
			'FIPRA United Kingdom (Unit)'                              => 'Michael Craven',
			'FIPRA Ukraine (Unit)'                                     => 'Ivan Poltavets',
			'FIPRA USA (Unit)'                                         => 'Rhod Shaw',
			'FIPRA Uzbekistan (Unit)'                                  => 'Evgeny Roshkov',
			'FIPRA Azerbaijan (Country Representative - Leila Alieva)' => 'Leila Alieva',
			'FIPRA Azerbaijan (Country Representative - Sadya Aliyev)' => 'Sadyar Aliyev',
			'FIPRA Colombia (Country Representative)'                  => 'Nicola Montorsi',
			'FIPRA Cyprus (Country Representative)'                    => 'Achilleas Demetriades',
			'FIPRA France (Country Representative)'                    => 'Jean-Francois Guichard',
			'FIPRA Georgia (Country Representative)'                   => 'Lasha Gogiberidze',
			'FIPRA Hong Kong (Country Representative)'                 => 'Greg Shea',
			'FIPRA Iceland (Country Representative)'                   => 'Alp Mehmet',
			'FIPRA Kazakhstan (Country Representative)'                => 'Ruslan Zhemkov',
			'FIPRA Luxembourg (Country Representative)'                => 'Joe Huggard',
			'FIPRA Malta (Country Representative)'                     => 'Martin Cauchi Inglott',
			'FIPRA Sweden (Country Representative)'                    => 'Anders Rostin',
			'FIPRA Tunisia (Country Representative)'                   => 'Ghazi Ben Ahmed',
			'FIPRA USA - California (Country Representative)'          => 'Rory Faber',
			'FIPRA USA - Texas (Country Representative)'               => 'Russ Keene',
		];

		$unit_rate_bands = [
			'FIPRA Argentina (Unit)'                                   => 'low',
			'FIPRA Australia (Unit)'                                   => 'high',
			'FIPRA Austria (Unit)'                                     => 'high',
			'FIPRA Brazil (Unit)'                                      => 'low',
			'FIPRA Bulgaria (Unit)'                                    => 'low',
			'FIPRA Canada (Unit)'                                      => 'high',
			'FIPRA China (Unit)'                                       => 'high',
			'FIPRA Croatia (Unit)'                                     => 'low',
			'FIPRA Czech Republic (Unit)'                              => 'low',
			'FIPRA Denmark (Unit)'                                     => 'high',
			'FIPRA Estonia (Unit)'                                     => 'low',
			'FIPRA Finland (Unit)'                                     => 'high',
			'FIPRA France (Unit)'                                      => 'high',
			'FIPRA Germany (Unit)'                                     => 'high',
			'FIPRA Greece (Unit)'                                      => 'low',
			'FIPRA Hungary (Unit)'                                     => 'low',
			'FIPRA India (Unit)'                                       => 'low',
			'FIPRA International BE (Unit)'                            => 'high',
			'FIPRA International UK (Unit)'                            => 'high',
			'FIPRA Ireland (Unit)'                                     => 'high',
			'FIPRA Italy (Unit)'                                       => 'high',
			'FIPRA Japan (Unit)'                                       => 'high',
			'FIPRA Kazakhstan (Unit)'                                  => 'low',
			'FIPRA Kyrgyzstan (Unit)'                                  => 'low',
			'FIPRA Latvia (Unit)'                                      => 'low',
			'FIPRA Lithuania (Unit)'                                   => 'low',
			'FIPRA Mongolia (Unit)'                                    => 'low',
			'FIPRA Mexico (Unit)'                                      => 'low',
			'FIPRA Netherlands (Unit)'                                 => 'high',
			'FIPRA Norway (Unit)'                                      => 'high',
			'FIPRA Poland (Unit)'                                      => 'low',
			'FIPRA Portugal (Unit)'                                    => 'low',
			'FIPRA Romania (Unit)'                                     => 'low',
			'FIPRA Russia (Unit)'                                      => 'low',
			'FIPRA Singapore (Unit)'                                   => 'high',
			'FIPRA Slovakia (Unit)'                                    => 'low',
			'FIPRA Slovenia (Unit)'                                    => 'low',
			'FIPRA South Africa (Unit)'                                => 'low',
			'FIPRA South Korea (Unit)'                                 => 'high',
			'FIPRA Spain (Unit)'                                       => 'low',
			'FIPRA Sweden (Unit)'                                      => 'high',
			'FIPRA Switzerland (Unit)'                                 => 'high',
			'FIPRA Tajikistan (Unit)'                                  => 'low',
			'FIPRA Turkey (Unit)'                                      => 'low',
			'FIPRA Turkmenistan (Unit)'                                => 'low',
			'FIPRA United Kingdom (Unit)'                              => 'high',
			'FIPRA Ukraine (Unit)'                                     => 'low',
			'FIPRA USA (Unit)'                                         => 'high',
			'FIPRA Uzbekistan (Unit)'                                  => 'low',
			'FIPRA Azerbaijan (Country Representative - Leila Alieva)' => 'low',
			'FIPRA Azerbaijan (Country Representative - Sadya Aliyev)' => 'low',
			'FIPRA Colombia (Country Representative)'                  => 'low',
			'FIPRA Cyprus (Country Representative)'                    => 'low',
			'FIPRA France (Country Representative)'                    => 'high',
			'FIPRA Georgia (Country Representative)'                   => 'low',
			'FIPRA Hong Kong (Country Representative)'                 => 'low',
			'FIPRA Iceland (Country Representative)'                   => 'low',
			'FIPRA Kazakhstan (Country Representative)'                => 'low',
			'FIPRA Luxembourg (Country Representative)'                => 'low',
			'FIPRA Malta (Country Representative)'                     => 'low',
			'FIPRA Sweden (Country Representative)'                    => 'high',
			'FIPRA Tunisia (Country Representative)'                   => 'low',
			'FIPRA USA - California (Country Representative)'          => 'high',
			'FIPRA USA - Texas (Country Representative)'               => 'high',
		];

		$lead_contact_emails = [
			'John Richardson'               => 'johnl.richardson@fipra.com',
			'José Gabriel Assis de Almeida' => 'jose.almeida@fipra.com',
			'Rositsa Velkova'               => 'rositsa.velkova@fipra.com',
			'Andre Albinati'                => 'andre.albinati@fipra.com',
			'Haiying Yuan'                  => 'haiying.yuan@fipra.com',
			'Natko Vlahovic'                => 'natko.vlahovic@fipra.com',
			'Andreas Hadjikyriacos'         => 'andreas.hadjikyriacos@fipra.com',
			'Jana Marco'                    => 'jana.marco@fipra.com',
			'Lars Abel'                     => 'lars.abel@fipra.com',
			'Andreas Kaju'                  => 'andreas.kaju@fipra.com',
			'Ilari Marzano'                 => 'ilari.marzano@fipra.com',
			'Jean Francois Guichard'        => 'jeanfrancois.guichard@fipra.com',
			'Dominik Meier'                 => 'dominik.meier@fipra.com',
			'Anthony Gortzis'               => 'anthony.gortzis@fipra.com',
			'Tamás Sárdi'                   => 'tamas.sardi@fipra.com',
			'Manash Neog'                   => 'manash.neog@fipra.com',
			'Peter-Carlo Lehrell'           => 'mark.fielding@fipra.com',
			'Ann Kelly'                     => 'ann.kelly@fipra.com',
			'Mariella Palazzolo'            => 'mariella.palazzolo@fipra.com',
			'Philip Howard'                 => 'philip.howard@fipra.com',
			'Yun-Hee Lee'                   => 'yunhee.lee@fipra.com',
			'Armands Gutmanis'              => 'armands.gutmanis@fipra.com',
			'Arūnas Pemkus'                 => 'arunas.pemkus@fipra.com',
			'Ukko Metsola'                  => 'ukko.metsola@fipra.com',
			'Miriam Offermans'              => 'miriam.offermans@fipra.com',
			'Per Høiby'                     => 'per.hoiby@fipra.com',
			'Marek Matraszek'               => 'marek.matraszek@fipra.com',
			'Ana Vila Nova'                 => 'ana.vilanova@fipra.com',
			'Alex Andreev'                  => 'alex.andreev@fipra.com',
			'Patrik Zoltvany'               => 'patrik.zoltvany@fipra.com',
			'Mihael Cigler'                 => 'mihael.cigler@fipra.com',
			'Sebastian Mariz'               => 'sebastian.mariz@fipra.com',
			'Göran Thorstenson'             => 'goran.thorstenson@fipra.com',
			'Dominique Reber'               => 'dominique.reber@fipra.com',
			'Ayse Aricioglu'                => 'ayse.aricioglu@fipra.com',
			'Rory Chisholm'                 => 'rory.chisholm@fipra.com',
			'Abdul Waheed Patel'            => 'abdulwaheed.patel@fipra.com',
			'Sayer Aliyev'                  => 'sayer.aliyev@fipra.com',
			'Richard Andrew'                => 'richard.andrew@fipra.com',
			'Jose Luis Echevarria'          => 'joseluis.echevarria@fipra.com',
			'Peter van Keulen'              => 'peter.vankeulen@fipra.com',
			'Anders Rostin'                 => 'anders.rostin@fipra.com',
			'Lasha Gogiberidze'             => 'lasha.gogiberidze@fipra.com',
			'Mark Fielding'                 => 'mark.fielding@fipra.com',
			'Markus Schindler'              => 'markus.schindler@fipra.com',
			'Ivan Poltavets'                => 'ivan.poltavets@fipra.com',
			'Rory Chisholm'                 => 'rory.chisholm@fipra.com',
			'Michael Craven'                => 'michael.craven@fipra.com',
			'Adrian Fielding'               => 'adrian.fielding@fipra.com',
			'Miguel Ángel Martínez'         => 'miguel.angelmartinez@fipra.com',
			'Danut Nicolae'                 => 'danut.nicolae@fipra.com',
			'Evgeny Roshkov'                => 'evgeny.roshkov@fipra.com',
			'Thaima Samman'                 => 'thaima.samman@fipra.com',
			'Lucinda Creighton'             => 'lucinda.creighton@fipra.com',
			'Michael Craven'                => 'michael.craven@fipra.com',
			'Yongbai Cho'                   => 'yongbai.cho@fipra.com',
			'Abdullah Nassief'              => 'abdullah.nassief@fipra.com',
			'Martin Cauchi Inglott'         => 'martin.cauchiinglott@fipra.com',
			'Joseph Chung'                  => 'joseph.chung@fipra.com',
			'Sadyar Aliyev'                 => 'sadyar.aliyev@fipra.com',
			'Nicola Montorsi'               => 'nicola.montorsi@fipra.com',
			'Achilleas Demetriades'         => 'achilleas.demetriades@fipra.com',
			'Jean-Francois Guichard'        => 'jeanfrancois.guichard@fipra.com',
			'Lasha Gogiberidze'             => 'lasha.gogiberidze@fipra.com',
			'Greg Shea'                     => 'greg.shea@fipra.com',
			'Alp Mehmet'                    => 'alp.mehmet@fipra.com',
			'Ruslan Zhemkov'                => 'ruslan.zhemkov@fipra.com',
			'Joe Huggard'                   => 'joe.huggard@fipra.com',
			'Martin Cauchi-Inglott'         => 'martin.cauchiinglott@fipra.com',
			'Anders Rostin'                 => 'anders.rostin@fipra.com',
			'Ghazi Ben Ahmed'               => 'ghazi.benahmed@fipra.com',
			'Rory Faber'                    => 'rory.faber@fipra.com',
			'Russ Keene'                    => 'russ.keene@fipra.com',
			'Marten Wennberg'               => 'marten.wennberg@fipra.com',
			'Leila Alieva'                  => 'leila.alieva@fipra.com',
			'Juan Mauricio Mora'            => 'jmmora@fipra.com',
			'Rhod Shaw'                     => 'rhod.shaw@fipra.com',
		];

		foreach ( $unit_lead_contacts as $unit => $contact ) {
			Unit_lead_contact::create(
				[
					'unit_name'         => $unit,
					'lead_contact_name' => $contact,
					'email'             => isset( $lead_contact_emails[ $contact ] ) ? $lead_contact_emails[ $contact ] : '',
					'rate_band'         => $unit_rate_bands[ $unit ],
				]
			);
		}
	}
}